--- 
app: 
  app_revision: 2.3.0_RC_1
qa2: 
  app_revision: 2.3.0_B_1
mnp: 
  app_revision: MNP_master
qa: 
  app_revision: 2.3.0_B_1
beta: 
  app_revision: 2.3.0_RC_1
production: 
  app_revision: 1.1.0_RC_0
cisco: 
  app_revision: cisco
acsi: 
  app_revision: ACSI_master
development: 
  app_revision: 1.1.1_D_25
testing: 
  app_revision: master
nightly: 
  app_revision: 1.1.1_B_80_parent_changes
honorstudentapp: 
  app_revision: 2.2.0_H_3
cucumber: 
  app_revision: 1.1.0_D_0
preview: 
  app_revision: 1.1.2-production
staging: 
  app_revision: 2.3.0_S_1
test: 
  app_revision: 1.1.0_D_0
solaro_india: 
  app_revision: solaro_india
