--- 
app: 
  app_revision: 2.1.0_RC_4
qa2: 
  app_revision: 2.2.0_B_2
mnp: 
  app_revision: MNP_master
qa: 
  app_revision: 2.2.0_B_2
beta: 
  app_revision: 2.1.0_RC_4
production: 
  app_revision: 1.1.0_RC_0
acsi: 
  app_revision: ACSI_master
development: 
  app_revision: 1.1.1_D_25
testing: 
  app_revision: master
nightly: 
  app_revision: 1.1.1_B_80_parent_changes
honorstudentapp: 
  app_revision: 1.0.0_TEST_HS_0
cucumber: 
  app_revision: 1.1.0_D_0
preview: 
  app_revision: 1.1.2-production
staging: 
  app_revision: 2.2.0_S_1
test: 
  app_revision: 1.1.0_D_0
honorstudent: 
  app_revision: honorstudent
