--- 
qa: 
  app_revision: TEST_RC_TAG
beta: 
  app_revision: TEST_RC_TAG
production: 
  app_revision: 1.1.0_RC_0
development: 
  app_revision: 1.1.1_D_25
testing: 
  app_revision: master
nightly: 
  app_revision: 1.1.1_B_80_parent_changes
cucumber: 
  app_revision: 1.1.0_D_0
preview: 
  app_revision: 1.1.2-production
staging: 
  app_revision: TEST_NIGHTLY_TAG
test: 
  app_revision: 1.1.0_D_0
